### ISSUE TITLE
[Not sure if related to mimimal_adb_fastboot] Bug: keyboard unresponsive after adb command

### ISSUE THREAD

**Issue by Smultie** [simmac/minimal_adb_fastboot#2]
Hey, not sure if this is at all related to your program, but my keyboard (MBP 13" 2010, OSX El Capitan Dev preview) gets unresponsive after a succesful adb or fastboot command. My trackpad as well.

My usb mouse still works on those occasions.

Any way to somehow find out what is causing this?

**Comment by simmac** [comment]
Hmm, maybe (hopefully) it's a bug in the beta of 10.11.
If not, it still would be a adb bug, not related to minimal_adb_fastboot.

**Comment by simmac** [comment]
@Smultie Just out of interest: Does this bug still exists?

**Comment by Smultie** [comment]
Not recently, but I got a new phone too (from Nexus 5 to Nexus 5X), so might be that that fixed it.

**Comment by simmac** [comment]
Okay, I will close this now as I cant't imagine it was related to the script anyway
