### ISSUE TITLE
Please include the aapt binary

### ISSUE THREAD

**Issue by IzzySoft** [simmac/minimal_adb_fastboot#3]
May I kindly suggest to have the `aapt` binary included as well? Often needed to get "basic details" from packages :)

**Comment by simmac** [comment]
I will add this in a seperate branch. Just a minute...

**Comment by simmac** [comment]
You can now download the tool from the [aapt](https://github.com/simmac/minimal_adb_fastboot/tree/aapt) branch to keep the master clean (most users just need adb and fastboot and it's not really an inconvenience for you and other aapt-users to switch the branch :wink: ).

**Comment by IzzySoft** [comment]
Thanks, @simmac (and sorry for the late response). Please note that at least for Linux, the `aapt` binary is dynamically linked against `lib/libc++.so` and won't run without that. I cannot test for Mac/Windows.
