### ISSUE TITLE
Something tricky happens when I try to run ./install.sh in Ubuntu

### ISSUE THREAD

**Issue by Ultrasteve** [simmac/minimal_adb_fastboot#4]
I have tried 'sudo' for serval time. But it just keep showing  'super user rights are needed.
You may be prompted for your admin password now.' And I have typed this in terminal---'sudo ./install.sh adb'
So, is there some way for me to solve this problem?

**Comment by simmac** [comment]
What happens if you run it without sudo?
So, just `$ ./install.sh adb`?
There should appear a prompt which says `Password:`, you type your admin password and confirm by pressing enter.

**Comment by blakete** [comment]
The install with the script on the Ubuntu subsystem for Windows fails. Any recommendations? 
Here is the output I am receiving:
![image](https://user-images.githubusercontent.com/49415344/58959224-79fd6700-8759-11e9-8317-702bf60000c3.png)

**Comment by JonnyTech** [comment]
Did you execute as super user (`sudo`)?

**Comment by blakete** [comment]
> Did you execute as super user (`sudo`)?

Yes, I did. Still got this error. Very odd.
